#
#   COMPONENT_NAME: somx
#
#   ORIGINS: 27
#
#
#    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# @(#) somx/makefile 2.6 12/26/95 17:57:40 [1/24/96 17:31:21]


# DISCLAIMER OF WARRANTIES.
# The following [enclosed] code is sample code created by IBM
# Corporation. This sample code is not part of any standard or IBM
# product and is provided to you solely for the purpose of assisting
# you in the development of your applications.  The code is provided
# "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
# THIS CODE.  IBM shall not be liable for any damages arising out of
# your use of the sample code, even if they have been advised of the
# possibility of such damages.
#
# DISTRIBUTION.
# This sample code can be freely distributed, copied, altered, and
# incorporated into other software, provided that it bears the above
# Copyright notice and DISCLAIMER intact.

OBJS	    = bt.obj helper.obj word.obj link.obj ll.obj fm.obj tpword.obj\
	      textline.obj colblk.obj page.obj ep.obj suep.obj footer.obj\
	      header.obj txtep.obj ipep.obj blep.obj main.obj
TARGET      = tp.exe
CLEANFILES  = bt.h word.h link.h ll.h fm.h tpword.h textline.h \
	      colblk.h page.h ep.h suep.h footer.h header.h txtep.h \
	      ipep.h blep.h

SCFLAGS     = -p -sh;ih
CC	    = icc
CFLAGS	    = -Q+ -W3 -D__MIG_LIB__
LINKER      = link386
LDFLAGS     = /packd /packc /exepack /align:16 /noi /m $(LDEBUG) /nol /PM:VIO 
LIBLIST     = $(SOMBASE)\lib\somtk os2386 

.SUFFIXES: .c .idl .ih .obj

.c.obj:
       $(CC) -I. $(SOMBASE)\include $(CFLAGS) -c $<

.idl.ih:
       sc $(SCFLAGS) $*.idl

$(TARGET): $(SOMBASE)\include\somcorba.bld $(OBJS)
	  $(LINKER) $(LDFLAGS) $(OBJS), $*, $*/m, $(LIBLIST), nul
	  $(TARGET)

clean:
	-del *.obj *.exe *.map *.ih $(CLEANFILES) >nul 2>&1

$(SOMBASE)\include\somcorba.bld:
	@echo This sample requires the CORBA-style C bindings
	@echo created using the somcorba command.
	@exit 1

bt.ih: bt.idl
bt.obj: bt.c bt.ih

helper.obj: helper.c helper.h

word.idl: bt.ih
word.ih: word.idl
word.obj: word.c word.ih

link.idl: bt.ih
link.ih: link.idl
link.obj: link.c link.ih

ll.idl: bt.ih
ll.ih: ll.idl
ll.obj: ll.c ll.ih

fm.ih: fm.idl
fm.obj: fm.c fm.ih

tpword.idl: word.ih
tpword.ih: tpword.idl
tpword.obj: tpword.c tpword.ih

textline.idl: ll.ih
textline.ih: textline.idl
textline.obj: textline.c textline.ih

colblk.idl: ll.ih
colblk.ih: colblk.idl
colblk.obj: colblk.c colblk.ih

page.ih: page.idl
page.obj: page.c page.ih

ep.ih: ep.idl
ep.obj: ep.c tpword.ih page.ih txtep.ih header.ih footer.ih ipep.ih blep.ih ep.ih

suep.idl: ep.ih
suep.ih: suep.idl
suep.obj: suep.c suep.ih

footer.idl: ep.ih
footer.ih: footer.idl
footer.obj: footer.c footer.ih page.ih tpword.ih

header.idl: ep.ih
header.ih: header.idl
header.obj: header.c header.ih

txtep.idl: ep.ih
txtep.ih: txtep.idl
txtep.obj: txtep.c txtep.ih

ipep.idl: txtep.ih
ipep.ih: ipep.idl
ipep.obj: ipep.c ipep.ih

blep.idl: txtep.ih
blep.ih: blep.idl
blep.obj: blep.c blep.ih

main.obj: main.c suep.ih

