DB2STOP
DB2 UPDATE DATABASE MANAGER CONFIGURATION USING TP_MON_NAME SOMTRXA
DB2START
DB2 DROP DATABASE TESTDB
DB2 CREATE DATABASE TESTDB
DB2 CONNECT TO TESTDB
DB2 CREATE TABLE USERID.PHONE (ID SMALLINT NOT NULL, NAME CHAR(20), PHONE_NUMBER CHAR(20), OFFICE SMALLINT, PRIMARY KEY (ID))
DB2 GRANT ALL ON TABLE USERID.PHONE TO PUBLIC
DB2 COMMIT
DB2 CONNECT RESET
