#
#   COMPONENT_NAME: somx
#
#   ORIGINS: 27
#
#
#    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# @(#) somx/makefile 2.8 12/26/95 17:59:26 [1/24/96 17:31:22]


# DISCLAIMER OF WARRANTIES.
# The following [enclosed] code is sample code created by IBM
# Corporation. This sample code is not part of any standard or IBM
# product and is provided to you solely for the purpose of assisting
# you in the development of your applications.  The code is provided
# "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
# THIS CODE.  IBM shall not be liable for any damages arising out of
# your use of the sample code, even if they have been advised of the
# possibility of such damages.
#
# DISTRIBUTION.
# This sample code can be freely distributed, copied, altered, and
# incorporated into other software, provided that it bears the above
# Copyright notice and DISCLAIMER intact.

#   Makefile for: derived    [Thu Jan 28 18:28:48 1993]

INCLUDEPATH = -I$(SOMBASE)\include
LIBDIRPATH  = $(SOMBASE)\lib

OBJS       = hello.obj mello.obj derived.obj main.obj
TARGET     = test.exe

CPPC       = icc
CPPFLAGS   = -D__cplusplus -c -fd
SCFLAGS     = -D__PRIVATE__
LINKER      = link386
LDFLAGS     = /packd /packc /exepack /align:16 /noi /m $(LDEBUG) /nol /PM:VIO 
LIBLIST     = $(LIBDIRPATH)\somtk os2386 

.SUFFIXES: .obj .cpp .idl .xh .xih

.cpp.obj:
	$(CPPC) -I. $(INCLUDEPATH) $(CPPFLAGS) $<
.idl.xh:
	  sc -sxh $(SCFLAGS) $*.idl
.idl.xih:
	  sc -sxih $(SCFLAGS) $*.idl

$(TARGET): $(SOMBASE)\include\somxh.bld $(OBJS)
	$(LINKER) $(LDFLAGS) $(OBJS), $*, $*/m, $(LIBLIST), nul
	$(TARGET)

clean:
	-del *.obj *.exe *.map *.xh *.xih $(CLEANFILES) >nul 2>&1

$(SOMBASE)\include\somxh.bld:
	@echo This sample requires the C++ bindings
	@echo created using the somxh command.
	@exit 1

hello.obj: hello.xh hello.xih hello.cpp
mello.obj: mello.xh mello.xih mello.cpp
derived.obj: derived.xh derived.xih derived.cpp
main.obj: derived.xh main.cpp

