#
#   COMPONENT_NAME: somx
#
#   ORIGINS: 27
#
#
#    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
#   All Rights Reserved
#   Licensed Materials - Property of IBM
#   US Government Users Restricted Rights - Use, duplication or
#   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# @(#) somx/makefile 2.6 12/26/95 17:50:55 [1/24/96 17:31:13]


# DISCLAIMER OF WARRANTIES.
# The following [enclosed] code is sample code created by IBM
# Corporation. This sample code is not part of any standard or IBM
# product and is provided to you solely for the purpose of assisting
# you in the development of your applications.  The code is provided
# "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
# THIS CODE.  IBM shall not be liable for any damages arising out of
# your use of the sample code, even if they have been advised of the
# possibility of such damages.
#
# DISTRIBUTION.
# This sample code can be freely distributed, copied, altered, and
# incorporated into other software, provided that it bears the above
# Copyright notice and DISCLAIMER intact.


OBJS       = animals.obj main.obj  
TARGET     = animals.exe
CLEANFILES = animals.h

SCFLAGS     = -p -sh;ih
CC	    = icc
CFLAGS	    = -Q+ -W3 -D__MIG_LIB__
LINKER      = link386
LDFLAGS     = /packd /packc /exepack /align:16 /noi /m $(LDEBUG) /nol /PM:VIO 
LIBLIST     = $(SOMBASE)\lib\somtk os2386 

.SUFFIXES: .c .idl .ih .obj

.c.obj:
	$(CC) -I. $(SOMBASE)\include $(CFLAGS) -c $<

.idl.ih:
	sc $(SCFLAGS) $*.idl

$(TARGET): $(SOMBASE)\include\somcorba.bld $(OBJS)
	 $(LINKER) $(LDFLAGS) $(OBJS), $*, $*/m, $(LIBLIST), nul
	 $(TARGET)

clean:
	-del *.obj *.exe *.map *.ih $(CLEANFILES) >nul 2>&1

$(SOMBASE)\include\somcorba.bld:
	@echo This sample requires the CORBA-style C bindings
	@echo created using the somcorba command.
	@exit 1

animals.ih: animals.idl

animals.obj: animals.c animals.ih

main.obj: main.c animals.h
