/*
 *
 *  25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996,1996
 *  All Rights Reserved
 *  Licensed Materials - Property of IBM
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 *
 *
 *  DISCLAIMER OF WARRANTIES.
 *  The following [enclosed] code is sample code created by IBM
 *  Corporation. This sample code is not part of any standard or IBM
 *  product and is provided to you solely for the purpose of assisting
 *  you in the development of your applications.  The code is provided
 *  "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 *  NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 *  THIS CODE.  IBM shall not be liable for any damages arising out of
 *  your use of the sample code, even if they have been advised of the
 *  possibility of such damages.
 *
 *  DISTRIBUTION.
 *  This sample code can be freely distributed, copied, altered, and
 *  incorporated into other software, provided that it bears the above
 *  Copyright notice and DISCLAIMER intact.
 */

#ifndef cont_idl
#define cont_idl

//
//  Interface : ContainedClass
//
//  Description : SampleClass's contained class
//

#include <somobj.idl>

#include <somestrm.idl>      // streaming

interface ContainedClass : CosStream::Streamable

{
  const long MAX_STRING_SIZE = 1024;
  attribute string name;

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_name, _set_name;

    // Class Modifiers:
    memory_management = corba;   // caller owns all returned memory
    dllname   = "samp.dll";      // loadable library of this class
    name: noset;

    // Overrides:
    somDefaultInit: override, init;     // Default object initializer
    somDestruct: override;              // Default object uninitializer
    override: externalize_to_stream, internalize_from_stream;
  };
#endif /* __SOMIDL__ */
};

#endif  /* cont_idl */
