/*
 *
 *  25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996,1996
 *  All Rights Reserved
 *  Licensed Materials - Property of IBM
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 *
 *
 *  DISCLAIMER OF WARRANTIES.
 *  The following [enclosed] code is sample code created by IBM
 *  Corporation. This sample code is not part of any standard or IBM
 *  product and is provided to you solely for the purpose of assisting
 *  you in the development of your applications.  The code is provided
 *  "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 *  NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 *  THIS CODE.  IBM shall not be liable for any damages arising out of
 *  your use of the sample code, even if they have been advised of the
 *  possibility of such damages.
 *
 *  DISTRIBUTION.
 *  This sample code can be freely distributed, copied, altered, and
 *  incorporated into other software, provided that it bears the above
 *  Copyright notice and DISCLAIMER intact.
 */

/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.45
 */

#ifndef SOM_Module_samp_Source
#define SOM_Module_samp_Source
#endif
#define SampleClass_Class_Source

#include "samp.xih"              // SampleClass include file
#include "cont.xh"                // ContainedClass include file

static string nilString = "";

#define EXTERNALIZE_STRING(strm, env, var) \
    if (var) \
        strm->write_string(env, var); \
    else \
        strm->write_string(env, nilString); \
    if ((ev)->_major != NO_EXCEPTION) \
        return;



/*
 *Method from the IDL attribute statement:
 *"attribute string name"
 */

SOM_Scope void  SOMLINK _set_name(SampleClass *somSelf,  Environment *ev,
                                  string name)
{
    SampleClassData *somThis = SampleClassGetData(somSelf);
    SampleClassMethodDebug("SampleClass","_set_name");

    if (somThis->name != NULL) SOMFree (somThis->name);
    somThis->name = (string) SOMMalloc(strlen(name));
    strcpy(somThis->name,name);

}


/*
 * Default object initializer
 */
SOM_Scope void SOMLINK somDefaultInit(SampleClass *somSelf, som3InitCtrl* ctrl)
{
    SampleClassData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    SampleClassMethodDebug("SampleClass","somDefaultInit");
    SampleClass_BeginInitializer_somDefaultInit;

    SampleClass_Init_CosStream_Streamable_somDefaultInit(somSelf, ctrl);

    /*
     * local SampleClass initialization code added by programmer
     */
    Environment *ev = somGetGlobalEnvironment();

    somThis->name = (char *)NULL;
    somThis->cc = (ContainedClass*) NULL;
}



/*
 * Default object uninitializer
 */
SOM_Scope void SOMLINK somDestruct(SampleClass *somSelf, octet doFree,
                                   som3DestructCtrl* ctrl)
{
    SampleClassData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    SampleClassMethodDebug("SampleClass","somDestruct");
    SampleClass_BeginDestructor;

    /*
     * local SampleClass deinitialization code added by programmer
     */

    if (somThis->name)
       SOMFree(somThis->name);
    if (somThis->cc)
       delete somThis->cc;

    SampleClass_EndDestructor;
}

//---------------------------------------------------------------------------
// Writing the object's state data to a stream
//---------------------------------------------------------------------------
SOM_Scope void  SOMLINK externalize_to_stream(SampleClass *somSelf,
                                               Environment *ev,
                                              CosStream_StreamIO* stream)
{
    SampleClassData *somThis = SampleClassGetData(somSelf);
    SampleClassMethodDebug("SampleClass","externalize_to_stream");

    SampleClass_parent_CosStream_Streamable_externalize_to_stream(somSelf,
                                                                  ev,
                                                                  stream);

    EXTERNALIZE_STRING(stream, ev, somThis->name);
    if ((ev)->_major != NO_EXCEPTION)
       return;

    somThis->cc->externalize_to_stream( ev,stream );
    if ((ev)->_major != NO_EXCEPTION)
       return;

 }


//---------------------------------------------------------------------------
// Reading the object's state data from a stream
//---------------------------------------------------------------------------
SOM_Scope void  SOMLINK internalize_from_stream(SampleClass *somSelf,
                                                 Environment *ev,
                                                CosStream_StreamIO* stream,
                                                CosLifeCycle_FactoryFinder* ff)
{
    SampleClassData *somThis = SampleClassGetData(somSelf);
    SampleClassMethodDebug("SampleClass","internalize_from_stream");

    SampleClass_parent_CosStream_Streamable_internalize_from_stream(somSelf,
                                                                    ev,
                                                                    stream,
                                                                    ff);

    somThis->name = stream->read_string(ev);
    if ((ev)->_major != NO_EXCEPTION)
       return;

    somThis->cc = new ContainedClass;
    somThis->cc->internalize_from_stream( ev, stream, ff );
    if ((ev)->_major != NO_EXCEPTION)
       return;
}
