
/*
 *  25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996,1996
 *  All Rights Reserved
 *  Licensed Materials - Property of IBM
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 *
 *
 *
 * DISCLAIMER OF WARRANTIES.
 * The following [enclosed] code is sample code created by IBM
 * Corporation. This sample code is not part of any standard or IBM
 * product and is provided to you solely for the purpose of assisting
 * you in the development of your applications.  The code is provided
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 * THIS CODE.  IBM shall not be liable for any damages arising out of
 * your use of the sample code, even if they have been advised of the
 * possibility of such damages.
 *
 * DISTRIBUTION.
 * This sample code can be freely distributed, copied, altered, and
 * incorporated into other software, provided that it bears the above
 * Copyright notice and DISCLAIMER intact.
 */

/************************************************************************************
 *
 *  Description of Interfaces defined in rental.idl (other interfaces for this sample
 *  are defined in rentalf.idl and rentalg.idl.
 *
 *
 *  RentalItem - A LifeCycle object defining the basic attributes of
 *               a video rental.
 *
 *  Movie - Adds 'movie' types of attributes to the RentalItem object.
 *
 *  Game  - Adds 'game' types of attributes to the RentalItem object.
 *
 *  RentObject - A LifeCycle object defining the basic attributes
 *               of a rental object used to check-in, check-out, etc.
 *
 *  CustomerAccount - A LifeCycle object defining the basic
 *                    attributes of an account that contains rental
 *                    information pertaining to specific customers.
 *
 *  GenericCounter  - A LifeCycle object used as a number/id counter.
 *
 *  RentalManager - Main interface that the client would program to for
 *                  managing the rental/customer/logs/etc objects.
 *
 ***********************************************************************************/




#ifndef SOM_rental_idl
#define SOM_rental_idl

#include <somlc.idl>      /* LifeCycle Service */

interface RentalLog;
interface CustomerLog;
interface RentalItemLog;
interface GenericRentalFactory;


interface RentalItem : somLifeCycle::LifeCycleObject
{
  //# Attributes

  attribute string title;
  attribute long id ;
  attribute short status;
  attribute string buyer;
  attribute long  num_times_rented;

  //# Methods

  string display();


#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_title, _set_title,
                  _get_id, _set_id,
                  _get_status, _set_status,
                  _get_buyer, _set_buyer,
                  _get_num_times_rented, _set_num_times_rented,
                  display;

    //# Class Modifiers
    functionprefix = RentalItems_;
    dllname = "rental.dll";

    //# Attribute Modifiers
    title: noget, noset;
    buyer: noget, noset;

    //# Method Modifiers
    somDefaultInit: override;
    somDestruct: override;

    baseproxyclass = "somLifeCycle::LifeCycleObject__Proxy";

  };
#endif /* __SOMIDL__ */
};


interface Movie : RentalItem
{
  //# Attributes

     attribute long category;
     attribute long rating;


#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_category, _set_category,
                  _get_rating, _set_rating;

    //# Class Modifiers
    functionprefix = Movies_;
    dllname = "rental.dll";
    factory=MovieFactory;

    //# Method Modifiers
    display: override;
    somDefaultInit: override;
    somDestruct: override;

  };
#endif /* __SOMIDL__ */
};


interface Game : RentalItem
{
  //# Attributes

     attribute long category;
     attribute long rating;

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_category, _set_category,
                  _get_rating, _set_rating;

    //# Class Modifiers
    functionprefix = Games_;
    dllname = "rental.dll";
    factory=GameFactory;

    //# Method Modifiers
    display: override;
    somDefaultInit: override;
    somDestruct: override;
  };
#endif /* __SOMIDL__ */
};


interface RentObject : somLifeCycle::LifeCycleObject
{
  //# Attributes

  attribute long rentalID;
  attribute string dueDate;
  attribute long CustomerID;

  //# Methods

  string display();


#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_rentalID, _set_rentalID,
                  _get_dueDate, _set_dueDate,
                  _get_CustomerID, _set_CustomerID,
                  display;

    //# Class Modifiers
    functionprefix = Rental_;
    dllname = "rental.dll";

    //# Attribute Modifier
    dueDate: noget, noset;

    //# Method Modifiers
    somDefaultInit: override;
    somDestruct: override;

    baseproxyclass = "somLifeCycle::LifeCycleObject__Proxy";

  };
#endif /* __SOMIDL__ */
};


interface CustomerAccount : somLifeCycle::LifeCycleObject
{
  //# Attributes

  attribute string firstName;
  attribute string lastName;
  attribute long CustomerID;
  attribute long Num_of_movies_rented;
  attribute long Num_of_games_rented;
  attribute long Num_of_delinquent_returns;

 //# Methods

  string rentalHistory();

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_firstName, _set_firstName,
                  _get_lastName, _set_lastName,
                  _get_CustomerID, _set_CustomerID,
                  _get_Num_of_movies_rented, _set_Num_of_movies_rented,
                  _get_Num_of_games_rented, _set_Num_of_games_rented,
                  _get_Num_of_delinquent_returns,_set_Num_of_delinquent_returns,
                  rentalHistory;



    //# Class Modifiers
    functionprefix = CustomerAccounts_;
    dllname = "rental.dll";

    //# Attribute Modifiers
    firstName: noget, noset;
    lastName: noget, noset;

    //# Method Modifiers
    somDefaultInit: override;
    somDestruct: override;

    baseproxyclass = "somLifeCycle::LifeCycleObject__Proxy";

  };
#endif /* __SOMIDL__ */
};


interface GenericCounter : somLifeCycle::LifeCycleObject
{
  //# Attributes

  attribute long counter;

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_counter, _set_counter;


    //# Class Modifiers
    functionprefix = GenericCntr_;
    dllname = "rental.dll";

    //# Method Modifiers
    somDefaultInit: override;
    somDestruct: override;

    baseproxyclass = "somLifeCycle::LifeCycleObject__Proxy";

  };
#endif /* __SOMIDL__ */
};


interface RentalManager : somLifeCycle::LifeCycleObject
{
  typedef RentObject * rentalobject;

  //# Attributes

  attribute  RentalLog               Rental_Log;
  attribute  RentalItemLog           RentalItem_Log;
  attribute  CustomerLog             Customer_Log;
  attribute  GenericCounter          Generic_Counter;
  attribute  GenericRentalFactory    GenericRental_Factory;

  //# Methods

  boolean check_out(in long cust_id,
                    in long rental_id);

  boolean check_in(in long rental_id);

  void purchase(in string title,
                in long category,
                in long rating,
                in string buyer,
                in char movie_or_game);

  string display_cust_info(in long cust_id);

  string display_rental_info(in long rental_id);

  void admin();

  void add_customer(in string lastnm,
                    in string firstnm,
                    in long cust_id);

  void remove_customer(in long cust_id);

  void remove_RentalItem(in long rental_id);


#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_Rental_Log, _set_Rental_Log,
                  _get_RentalItem_Log, _set_RentalItem_Log,
                  _get_Customer_Log, _set_Customer_Log,
                  _get_Generic_Counter, _set_Generic_Counter,
                  _get_GenericRental_Factory, _set_GenericRental_Factory,
                  check_out,
                  check_in,
                  purchase,
                  display_cust_info,
                  display_rental_info,
                  admin,
                  add_customer,
                  remove_customer,
                  remove_RentalItem;

    //# Class Modifiers
    functionprefix = RentalMgr_;
    dllname = "rental.dll";

    //# Attribute Modifiers
    Rental_Log: noget;
    RentalItem_Log: noget;
    Customer_Log: noget;

    //# Method Modifiers
    somDefaultInit: override;
    somDestruct: override;

    baseproxyclass = "somLifeCycle::LifeCycleObject__Proxy";

  };
#endif /* __SOMIDL__ */
};

#endif  /* SOM_rental_idl */

